---
title: "Aria_project2"
author: "Aria"
date: "2023-09-12"
output: 
  html_document: 
    toc: yes
---

## Q1:JWHT Chapter 2, Exercise 5
### 1.1.pros and cons of a flexible approach for regression or classification
#### pros
Flexible approach are able to adapt to the complexity of the data and can model a wide range of underlying data distributions. They do not make assumptions about the underlying probability distribution of the data and can model non-linear or non-additive relationships between the input features and output variable.
#### cons
These methods can be computationally intensive and may not be as interpretable as parametric models.

### 1.2. Under what circumstances might a more flexible approach be preferred to a less flexible approach?
A flexible approach is  particularly useful when the data is complex and the assumptions of parametric models are not met.

### 1.3.When might a less flexible approach be preferred?
A less flexible approach is particularly useful when the data is simple and the assumptions of the model are met. 


## Q2:Faraway Chapter 2. Exercise 2.
```{r}
install.packages("faraway")
library("faraway")

dat <- faraway::uswages
m1 <- lm(wage ~ educ + exper, data = dat)

library(ggplot2)
install.packages("ggpubr")
library(ggpubr)

plot1 <- ggplot(dat, aes(x = x , y = y)) +
  geom_point() +
  stat_smooth(method = "lm") +
  stat_regline_equation(label.x.npc = "center")
plot1
```

